plugins {
    id 'spring-boot-common-conventions'
}

dependencies {
    implementation 'kh.edu.istad:customer-domain-core'
    implementation 'kh.edu.istad:customer-application-service'
    implementation 'kh.edu.istad:customer-service-message'
    implementation 'kh.edu.istad:customer-service-persistance'
    implementation 'kh.edu.istad:customer-service-restapi'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}