server:
  port: 8092


# Database Toggle
persistence:
    db-type: mongo

spring:
  application:
    name: customer-service
  mongodb:
    host: localhost
    port: 27018
    username: mongo
    password: admin
    database: db_customer
    authentication-database: admin
    representation: # MongoDB BSON needs to know what binary format to use when storing Java UUIDs
      uuid: standard

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/app_db
    username: admin
    password: postgres@123456789


#  datasource:
#    url: jdbc:postgresql://localhost:5432/app_db
#    username: admin
#    password: postgres@123456789
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true