pluginManagement {
    includeBuild('../build-logic')

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'infrastructure'

include 'api-gateway'
include 'config-server'